/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OtherID = IDL.Record({
  'issueDate' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'expiryDate' : IDL.Text,
  'fullName' : IDL.Text,
  'idNumber' : IDL.Text,
  'issuedBy' : IDL.Text,
  'photo' : ExternalBlob,
  'idType' : IDL.Text,
});
export const CollegeStudentID = IDL.Record({
  'branch' : IDL.Text,
  'enrollmentNo' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'collegeName' : IDL.Text,
  'fullName' : IDL.Text,
  'academicYear' : IDL.Text,
  'photo' : ExternalBlob,
  'course' : IDL.Text,
  'validUntil' : IDL.Text,
});
export const IDType = IDL.Variant({
  'other' : OtherID,
  'collegeStudent' : CollegeStudentID,
});
export const Time = IDL.Int;
export const IDCard = IDL.Record({
  'id' : IDL.Text,
  'cardType' : IDType,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCollegeID' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createOtherID' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteCard' : IDL.Func([IDL.Text], [], []),
  'getAllCards' : IDL.Func([], [IDL.Vec(IDCard)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCard' : IDL.Func([IDL.Text], [IDCard], ['query']),
  'getSortedCards' : IDL.Func([IDL.Text], [IDL.Vec(IDCard)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCard' : IDL.Func([IDL.Text, IDCard], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OtherID = IDL.Record({
    'issueDate' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'expiryDate' : IDL.Text,
    'fullName' : IDL.Text,
    'idNumber' : IDL.Text,
    'issuedBy' : IDL.Text,
    'photo' : ExternalBlob,
    'idType' : IDL.Text,
  });
  const CollegeStudentID = IDL.Record({
    'branch' : IDL.Text,
    'enrollmentNo' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'collegeName' : IDL.Text,
    'fullName' : IDL.Text,
    'academicYear' : IDL.Text,
    'photo' : ExternalBlob,
    'course' : IDL.Text,
    'validUntil' : IDL.Text,
  });
  const IDType = IDL.Variant({
    'other' : OtherID,
    'collegeStudent' : CollegeStudentID,
  });
  const Time = IDL.Int;
  const IDCard = IDL.Record({
    'id' : IDL.Text,
    'cardType' : IDType,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCollegeID' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createOtherID' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteCard' : IDL.Func([IDL.Text], [], []),
    'getAllCards' : IDL.Func([], [IDL.Vec(IDCard)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCard' : IDL.Func([IDL.Text], [IDCard], ['query']),
    'getSortedCards' : IDL.Func([IDL.Text], [IDL.Vec(IDCard)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCard' : IDL.Func([IDL.Text, IDCard], [], []),
  });
};

export const init = ({ IDL }) => { return []; };