/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CollegeStudentID {
  'branch' : string,
  'enrollmentNo' : string,
  'dateOfBirth' : string,
  'collegeName' : string,
  'fullName' : string,
  'academicYear' : string,
  'photo' : ExternalBlob,
  'course' : string,
  'validUntil' : string,
}
export type ExternalBlob = Uint8Array;
export interface IDCard {
  'id' : string,
  'cardType' : IDType,
  'timestamp' : Time,
}
export type IDType = { 'other' : OtherID } |
  { 'collegeStudent' : CollegeStudentID };
export interface OtherID {
  'issueDate' : string,
  'dateOfBirth' : string,
  'expiryDate' : string,
  'fullName' : string,
  'idNumber' : string,
  'issuedBy' : string,
  'photo' : ExternalBlob,
  'idType' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCollegeID' : ActorMethod<
    [
      string,
      ExternalBlob,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'createOtherID' : ActorMethod<
    [
      string,
      ExternalBlob,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'deleteCard' : ActorMethod<[string], undefined>,
  'getAllCards' : ActorMethod<[], Array<IDCard>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCard' : ActorMethod<[string], IDCard>,
  'getSortedCards' : ActorMethod<[string], Array<IDCard>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCard' : ActorMethod<[string, IDCard], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];